### Dataset ###
data:
  name: custom
  folder: ./datasets/Weather

### Pretrain ###
train:
  epochs: 200
  batch_size: 256
  lr: 1.0e-3
  itr_per_epoch: 1.0e+8
  model_path: ""
  output_folder: pretrain
  val_epoch_interval: 10
  display_interval: 1
